# Generated by Django 2.2.6 on 2019-10-20 08:29

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sandyuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='sandyuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='sandyuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sandyuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='sandyuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='sandyuser',
            name='status',
            field=models.CharField(default='Some cool status', max_length=120, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='sandyuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='username'),
        ),
    ]
