# Generated by Django 2.2.6 on 2019-10-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20191020_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
