# Generated by Django 2.2.7 on 2019-11-30 23:21

from django.db import migrations
import user_app.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20191120_0931'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sandyuser',
            managers=[
                ('objects', user_app.managers.SandyUserManager()),
            ],
        ),
    ]
